name: Prepare Upgrade (Creates a PR to upgrade LingView core to the newest stable version available)

env:
  upstream: BrownCLPS/LingView
  upstream_branch: master
  base_branch: master
  pr_branch: master-upgrade

on: workflow_dispatch 

jobs:
  check-actor:
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check-repo:
    runs-on: ubuntu-latest
    outputs:
      is-core: ${{ github.repository == env.upstream }}
    steps:
      - name: Log result
        run: 'echo "Checking if repository is the upstream repository... $answer"'
        env:
          answer: ${{ github.repository == env.upstream }}
  upgrade:
    needs: [check-actor, check-repo]
    if: needs.check-repo.outputs.is-core == 'false'
    runs-on: ubuntu-latest
    env:
      actor: ${{ github.actor }}
      actoremail: ${{ github.actor }}@users.noreply.github.com
    steps:
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.base_branch }}
          fetch-depth: 0 # fetch the whole history (necessary for merge)
      - name: Merge upstream into base branch
        run: |
          git config user.email "$actoremail"
          git config user.name "$actor"
          git remote add upstream "https://github.com/$upstream.git"
          git fetch upstream
          echo "remote_head_hash=$(git rev-parse "upstream/$upstream_branch")" >> $GITHUB_ENV
          git merge --no-commit --no-ff -Xtheirs "upstream/$upstream_branch" || echo "There are unresolved merge conflicts. Make sure you resolve them before merging the pull request."
          # revert any updates in data path and build path
          git reset -- build # build is gitignored, but sometimes causes merge conflicts anyway *shrug*
          git reset -- data
          git checkout -- data
          # revert any updates to translated text (in LocaleConstants, LocaleSelect, About, Glossary, and Landing files)
          git reset -- jsx/App/locale/LocaleConstants.jsx
          git reset -- jsx/App/locale/LocaleSelect.jsx
          git reset -- jsx/App/AboutPage.jsx
          git reset -- jsx/App/GlossaryPage.jsx
          git reset -- jsx/App/LandingPage.jsx
          git checkout -- jsx/App/locale/LocaleConstants.jsx
          git checkout -- jsx/App/locale/LocaleSelect.jsx
          git checkout -- jsx/App/AboutPage.jsx
          git checkout -- jsx/App/GlossaryPage.jsx
          git checkout -- jsx/App/LandingPage.jsx
          # warn about any workflow changes, then discard them
          (test $(git status | grep -c workflows) -lt 1 && \
          echo workflows_message="" >> $GITHUB_ENV) || \
          echo workflows_message="There were workflow changes, which can't be included in the automated PR. You will need to manually update your files in .github/workflows to match the ${{ env.upstream }} version." >> $GITHUB_ENV
          git reset -- .github/workflows
          git checkout -- .github/workflows
          # warn about any remaining unresolved merge conflicts
          (test $(git status | grep -c unmerged) -lt 1 &&\
          echo conflicts_message="" >> $GITHUB_ENV) || \
          echo conflicts_message="IMPORTANT: There are unresolved merge conflicts. Before merging this pull request, resolve them by making additional commits to the ${{ env.pr_branch }} branch." >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Upgrade LingView core version
          committer: GitHub <noreply@github.com>
          title: 'Upgrade LingView Core'
          body: |
            Pull request to upgrade LingView version to `${{ env.upstream_branch }}` (${{ env.remote_head_hash }}) is ready to review and merge!
            
            > I automatically ignored any changes made to the `data/` folder, so your FLEx and ELAN files will not be changed. :)
            > 
            > When you review this, please make sure I didn't accidentally undo any of your LingView customizations (e.g. if your `index.html` or `jsx/App/AboutPage.jsx` is different from the version at `${{ env.upstream }}`)!
            > 
            > ${{ env.conflicts_message }} 
            > 
            > ${{ env.workflows_message }}

            _Auto-generated by [create-pull-request][1]_

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automated pr
          branch: ${{ env.pr_branch }}
