name: Prepare Upgrade (Creates a PR to upgrade LingView core to the newest stable version available)

env:
  upstream: BrownCLPS/LingView
  upstream_branch: master
  base_branch: master
  pr_branch: master-upgrade

on: workflow_dispatch 

jobs:
  check-actor:
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check-repo:
    runs-on: ubuntu-latest
    outputs:
      is-core: ${{ github.repository == env.upstream }}
    steps:
      - name: Log result
        run: 'echo "Checking if repository is the upstream repository... $answer"'
        env:
          answer: ${{ github.repository == env.upstream }}
  upgrade:
    needs: [check-actor, check-repo]
    if: needs.check-repo.outputs.is-core == 'false'
    runs-on: ubuntu-latest
    env:
      actor: ${{ github.actor }}
      actoremail: ${{ github.actor }}@users.noreply.github.com
    steps:
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.base_branch }}
          fetch-depth: 0 # fetch the whole history (necessary for merge)
      - name: Merge upstream into base branch
        run: |
          git config user.email "$actoremail"
          git config user.name "$actor"
          git remote add upstream "https://github.com/$upstream.git"
          git fetch upstream
          remote_head_hash=$(git rev-parse "upstream/$upstream_branch")
          echo "::set-env name=remote_head_hash::$remote_head_hash"
          git merge --no-commit --no-ff "upstream/$upstream_branch"
          # revert any updates in data path
          git reset -- data
          git checkout -- data
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Upgrade LingView core version
          committer: GitHub <noreply@github.com>
          author: ${{ env.actor }} <${{ env.actoremail }}>
          title: 'Upgrade LingView Core'
          body: |
            Pull request to upgrade LingView version to `${{ env.upstream_branch }}` (${{ env.remote_head_hash }}) is ready to review and merge!
            
            > _Automatically ignored any changes made to the `data/` folder._
            > Ensure that fork-specific changes (e.g. a customized `index.html` or `jsx/App/AboutPage.jsx`) are preserved.

            _Auto-generated by [create-pull-request][1]_

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automated pr
          branch: ${{ env.pr_branch }}
